/*
 * generated by Xtext
 */
package fr.inria.lang.ui.contentassist

import fr.inria.lang.ui.contentassist.AbstractVMProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class VMProposalProvider extends AbstractVMProposalProvider {
}
