/**
 * generated by Xtext
 */
package fr.inria.lang.validation;

import fr.inria.lang.validation.AbstractVMValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class VMValidator extends AbstractVMValidator {
}
